<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        // Skip if already seeded to prevent duplicates on container restarts
        if (\App\Models\Property::count() > 0) {
            return;
        }

        $owner = User::firstOrCreate(
            ['email' => 'owner@realestate.com'],
            ['name' => 'Demo Owner', 'password' => Hash::make('password')]
        );

        $user2 = User::firstOrCreate(
            ['email' => 'buyer@realestate.com'],
            ['name' => 'Demo Buyer', 'password' => Hash::make('password')]
        );

        $properties = [
            [
                'title'        => 'Modern Family Home in Quezon City',
                'description'  => 'A stunning 4-bedroom modern home with open floor plan, large backyard, and premium finishes throughout. Perfect for growing families.',
                'type'         => 'house',
                'listing_type' => 'sale',
                'price'        => 8500000,
                'address'      => '123 Commonwealth Ave',
                'city'         => 'Quezon City',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1121',
                'latitude'     => 14.6760,
                'longitude'    => 121.0437,
                'bedrooms'     => 4,
                'bathrooms'    => 3,
                'area_sqft'    => 2400,
                'parking_spots'=> 2,
                'is_furnished' => false,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
                'amenities'    => ['Swimming Pool', 'Garden', 'Security System', 'Solar Panels'],
            ],
            [
                'title'        => 'Cozy Studio in Makati CBD',
                'description'  => 'Fully furnished studio unit in the heart of Makati. Walking distance to BGC, Greenbelt, and major offices.',
                'type'         => 'studio',
                'listing_type' => 'rent',
                'price'        => 25000,
                'address'      => '88 Ayala Ave',
                'city'         => 'Makati',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1226',
                'latitude'     => 14.5547,
                'longitude'    => 121.0244,
                'bedrooms'     => 0,
                'bathrooms'    => 1,
                'area_sqft'    => 350,
                'parking_spots'=> 1,
                'is_furnished' => true,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
                'amenities'    => ['Gym', 'Pool', 'Concierge', 'CCTV', 'Smart Locks'],
            ],
            [
                'title'        => 'Beachfront Villa in Boracay',
                'description'  => 'Luxurious 5-bedroom beachfront villa with private pool and direct beach access. Ideal for vacation rental or personal retreat.',
                'type'         => 'villa',
                'listing_type' => 'sale',
                'price'        => 35000000,
                'address'      => 'Station 1, White Beach',
                'city'         => 'Boracay',
                'state'        => 'Aklan',
                'country'      => 'Philippines',
                'zip_code'     => '5608',
                'latitude'     => 11.9674,
                'longitude'    => 121.9248,
                'bedrooms'     => 5,
                'bathrooms'    => 5,
                'area_sqft'    => 4500,
                'parking_spots'=> 3,
                'is_furnished' => true,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
                'amenities'    => ['Private Pool', 'Beach Access', 'Full Kitchen', 'Staff Quarters', 'Outdoor Shower'],
            ],
            [
                'title'        => '2BR Condo in BGC Taguig',
                'description'  => 'Well-maintained 2-bedroom condo in Bonifacio Global City. High floor with city views, near malls, restaurants, and tech hubs.',
                'type'         => 'condo',
                'listing_type' => 'rent',
                'price'        => 45000,
                'address'      => '30th Street, BGC',
                'city'         => 'Taguig',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1634',
                'latitude'     => 14.5502,
                'longitude'    => 121.0487,
                'bedrooms'     => 2,
                'bathrooms'    => 2,
                'area_sqft'    => 850,
                'parking_spots'=> 1,
                'is_furnished' => true,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
                'amenities'    => ['Gym', 'Co-working Space', 'Rooftop Deck', 'Laundry'],
            ],
            [
                'title'        => 'Farm Lot in Batangas',
                'description'  => 'Titled agricultural land perfect for farming, resort development, or eco-retreat. Flat terrain with mountain views.',
                'type'         => 'land',
                'listing_type' => 'sale',
                'price'        => 3200000,
                'address'      => 'Brgy. San Isidro',
                'city'         => 'Nasugbu',
                'state'        => 'Batangas',
                'country'      => 'Philippines',
                'zip_code'     => '4231',
                'latitude'     => 14.0693,
                'longitude'    => 120.6229,
                'bedrooms'     => 0,
                'bathrooms'    => 0,
                'area_sqft'    => 10000,
                'parking_spots'=> 0,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
                'amenities'    => ['Road Access', 'Water Source', 'Titled'],
            ],
            [
                'title'        => 'Spacious Apartment in Cebu City',
                'description'  => 'Bright and spacious 3-bedroom apartment in a quiet neighborhood. Close to IT Park, SM, and Ayala Center Cebu.',
                'type'         => 'apartment',
                'listing_type' => 'rent',
                'price'        => 32000,
                'address'      => '45 Escario Street',
                'city'         => 'Cebu City',
                'state'        => 'Cebu',
                'country'      => 'Philippines',
                'zip_code'     => '6000',
                'latitude'     => 10.3157,
                'longitude'    => 123.8854,
                'bedrooms'     => 3,
                'bathrooms'    => 2,
                'area_sqft'    => 1200,
                'parking_spots'=> 1,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
                'amenities'    => ['Backup Power', 'CCTV', 'Near Schools'],
            ],
        ];

        foreach ($properties as $data) {
            $owner->properties()->create($data);
        }

        $properties2 = [
            [
                'title'        => 'Hilltop House with Ocean View in Baguio',
                'description'  => 'Charming 3-bedroom house nestled in a pine forest with panoramic views of Baguio and Benguet. Cool climate all year round.',
                'type'         => 'house',
                'listing_type' => 'sale',
                'price'        => 12500000,
                'address'      => '22 Leonard Wood Road',
                'city'         => 'Baguio City',
                'state'        => 'Benguet',
                'country'      => 'Philippines',
                'zip_code'     => '2600',
                'latitude'     => 16.4023,
                'longitude'    => 120.5960,
                'bedrooms'     => 3,
                'bathrooms'    => 2,
                'area_sqft'    => 1800,
                'parking_spots'=> 2,
                'is_furnished' => true,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
                'amenities'    => ['Fireplace', 'Garden', 'Mountain View', 'Backup Generator'],
            ],
            [
                'title'        => 'Luxury Penthouse in Eastwood City',
                'description'  => 'Fully furnished penthouse with 3 bedrooms, private terrace, and 360° city view. High-end appliances, concierge, and premium amenities included.',
                'type'         => 'condo',
                'listing_type' => 'rent',
                'price'        => 120000,
                'address'      => 'Eastwood Cyber One',
                'city'         => 'Quezon City',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1110',
                'latitude'     => 14.6091,
                'longitude'    => 121.0814,
                'bedrooms'     => 3,
                'bathrooms'    => 3,
                'area_sqft'    => 2200,
                'parking_spots'=> 2,
                'is_furnished' => true,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
                'amenities'    => ['Private Terrace', 'Infinity Pool', 'Gym', 'Concierge', 'Smart Home'],
            ],
            [
                'title'        => 'Townhouse for Sale in Alabang',
                'description'  => 'Well-maintained 3-bedroom townhouse in a gated subdivision in Alabang. Near malls, international schools, and major expressways.',
                'type'         => 'house',
                'listing_type' => 'sale',
                'price'        => 9800000,
                'address'      => '7 Acacia Lane, Alabang Hills',
                'city'         => 'Muntinlupa',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1780',
                'latitude'     => 14.4081,
                'longitude'    => 121.0447,
                'bedrooms'     => 3,
                'bathrooms'    => 2,
                'area_sqft'    => 1600,
                'parking_spots'=> 2,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'amenities'    => ['Clubhouse', 'Basketball Court', 'CCTV', 'Gated Community'],
            ],
            [
                'title'        => '1BR Condo for Rent near Ortigas',
                'description'  => 'Modern 1-bedroom unit in a high-rise condo along EDSA near Ortigas. Fully furnished with fiber internet and city view.',
                'type'         => 'condo',
                'listing_type' => 'rent',
                'price'        => 28000,
                'address'      => '1200 EDSA, Mandaluyong',
                'city'         => 'Mandaluyong',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1550',
                'latitude'     => 14.5832,
                'longitude'    => 121.0564,
                'bedrooms'     => 1,
                'bathrooms'    => 1,
                'area_sqft'    => 480,
                'parking_spots'=> 1,
                'is_furnished' => true,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80',
                'amenities'    => ['Fiber Internet', 'Pool', 'Gym', 'Laundry Area'],
            ],
            [
                'title'        => 'Seafront Lot in Palawan',
                'description'  => 'Prime beachfront lot in El Nido, Palawan. Crystal-clear water, pristine white sand. Ideal for resort or eco-lodge development.',
                'type'         => 'land',
                'listing_type' => 'sale',
                'price'        => 18000000,
                'address'      => 'Brgy. Corong-Corong',
                'city'         => 'El Nido',
                'state'        => 'Palawan',
                'country'      => 'Philippines',
                'zip_code'     => '5313',
                'latitude'     => 11.1784,
                'longitude'    => 119.3968,
                'bedrooms'     => 0,
                'bathrooms'    => 0,
                'area_sqft'    => 15000,
                'parking_spots'=> 0,
                'is_furnished' => false,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
                'amenities'    => ['Beach Access', 'Sea View', 'Road Access', 'Titled'],
            ],
            [
                'title'        => 'Family Home for Rent in Davao City',
                'description'  => 'Spacious 4-bedroom house in a quiet subdivision in Davao. Large living areas, covered garage, and well-maintained garden.',
                'type'         => 'house',
                'listing_type' => 'rent',
                'price'        => 38000,
                'address'      => '52 Ilustre Street, Agdao',
                'city'         => 'Davao City',
                'state'        => 'Davao del Sur',
                'country'      => 'Philippines',
                'zip_code'     => '8000',
                'latitude'     => 7.1907,
                'longitude'    => 125.4553,
                'bedrooms'     => 4,
                'bathrooms'    => 3,
                'area_sqft'    => 2000,
                'parking_spots'=> 2,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800&q=80',
                'amenities'    => ['Garden', 'Covered Garage', 'Near Market', 'CCTV'],
            ],
            [
                'title'        => 'Investment Condo in Iloilo City',
                'description'  => 'Brand-new studio unit in the rapidly developing Iloilo Business Park. Great for investment — projected high rental yield.',
                'type'         => 'studio',
                'listing_type' => 'sale',
                'price'        => 3800000,
                'address'      => 'Iloilo Business Park, Mandurriao',
                'city'         => 'Iloilo City',
                'state'        => 'Iloilo',
                'country'      => 'Philippines',
                'zip_code'     => '5000',
                'latitude'     => 10.7202,
                'longitude'    => 122.5621,
                'bedrooms'     => 0,
                'bathrooms'    => 1,
                'area_sqft'    => 280,
                'parking_spots'=> 0,
                'is_furnished' => true,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
                'amenities'    => ['Pool', 'Gym', 'Sky Lounge', 'Near Airport'],
            ],
            [
                'title'        => 'Modern Villa in Tagaytay',
                'description'  => 'Breathtaking 4-bedroom villa overlooking Taal Volcano. Perfect weekend home or vacation rental with cool breeze year-round.',
                'type'         => 'villa',
                'listing_type' => 'sale',
                'price'        => 22000000,
                'address'      => 'Brgy. Silang Junction South',
                'city'         => 'Tagaytay',
                'state'        => 'Cavite',
                'country'      => 'Philippines',
                'zip_code'     => '4120',
                'latitude'     => 14.1153,
                'longitude'    => 120.9621,
                'bedrooms'     => 4,
                'bathrooms'    => 4,
                'area_sqft'    => 3200,
                'parking_spots'=> 3,
                'is_furnished' => true,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
                'amenities'    => ['Volcano View', 'Private Pool', 'Fireplace', 'BBQ Area', 'Garden'],
            ],
            [
                'title'        => 'Affordable 2BR in Las Piñas',
                'description'  => 'Newly renovated 2-bedroom apartment in a secure compound in Las Piñas. Convenient location near major roads and commercial centers.',
                'type'         => 'apartment',
                'listing_type' => 'rent',
                'price'        => 18000,
                'address'      => '10 BF Resort Drive',
                'city'         => 'Las Piñas',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1740',
                'latitude'     => 14.4453,
                'longitude'    => 120.9832,
                'bedrooms'     => 2,
                'bathrooms'    => 1,
                'area_sqft'    => 700,
                'parking_spots'=> 1,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800&q=80',
                'amenities'    => ['Water 24/7', 'Security Guard', 'Near LRT Station'],
            ],
            [
                'title'        => 'Commercial Lot for Sale in Pasig',
                'description'  => 'High-visibility commercial lot along Ortigas Avenue Extension, ideal for retail, office, or mixed-use development.',
                'type'         => 'land',
                'listing_type' => 'sale',
                'price'        => 25000000,
                'address'      => 'Ortigas Ave Extension, Ugong',
                'city'         => 'Pasig',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1604',
                'latitude'     => 14.5764,
                'longitude'    => 121.0851,
                'bedrooms'     => 0,
                'bathrooms'    => 0,
                'area_sqft'    => 8000,
                'parking_spots'=> 0,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
                'amenities'    => ['Corner Lot', 'Main Road Frontage', 'Titled', 'Near BGC'],
            ],
            [
                'title'        => 'Condo Studio for Sale in Pasay',
                'description'  => 'Affordable pre-selling studio unit near Mall of Asia, perfect for first-time buyers or investors looking for rental income.',
                'type'         => 'studio',
                'listing_type' => 'sale',
                'price'        => 2900000,
                'address'      => 'Macapagal Blvd, Seaside',
                'city'         => 'Pasay',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1300',
                'latitude'     => 14.5378,
                'longitude'    => 120.9836,
                'bedrooms'     => 0,
                'bathrooms'    => 1,
                'area_sqft'    => 260,
                'parking_spots'=> 0,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
                'amenities'    => ['Pool', 'Gym', 'Near MOA', 'Near Airport'],
            ],
            [
                'title'        => '3BR House in General Trias, Cavite',
                'description'  => 'Brand-new 3-bedroom single attached house in a master-planned community. Near CALAX exit and upcoming industrial zones.',
                'type'         => 'house',
                'listing_type' => 'sale',
                'price'        => 6500000,
                'address'      => 'Brgy. Buenavista III',
                'city'         => 'General Trias',
                'state'        => 'Cavite',
                'country'      => 'Philippines',
                'zip_code'     => '4107',
                'latitude'     => 14.3861,
                'longitude'    => 120.8817,
                'bedrooms'     => 3,
                'bathrooms'    => 2,
                'area_sqft'    => 1200,
                'parking_spots'=> 1,
                'is_furnished' => false,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
                'amenities'    => ['Clubhouse', 'Basketball Court', 'Park', 'Gated Community'],
            ],
            [
                'title'        => 'Beachside Apartment in Lapu-Lapu, Cebu',
                'description'  => 'Furnished 2-bedroom apartment steps from Mactan Beach. Ideal for vacationers or expats. Near Mactan-Cebu International Airport.',
                'type'         => 'apartment',
                'listing_type' => 'rent',
                'price'        => 35000,
                'address'      => 'Brgy. Punta Engaño, Mactan',
                'city'         => 'Lapu-Lapu City',
                'state'        => 'Cebu',
                'country'      => 'Philippines',
                'zip_code'     => '6015',
                'latitude'     => 10.2969,
                'longitude'    => 124.0018,
                'bedrooms'     => 2,
                'bathrooms'    => 2,
                'area_sqft'    => 950,
                'parking_spots'=> 1,
                'is_furnished' => true,
                'is_featured'  => true,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
                'amenities'    => ['Beach Access', 'Sea View', 'Pool', 'Near Airport'],
            ],
            [
                'title'        => 'Office Space for Rent in Pasig IT Park',
                'description'  => 'Fitted office space on the 10th floor of a Grade A building in Pasig IT Park. Suitable for BPOs, startups, and corporate tenants.',
                'type'         => 'commercial',
                'listing_type' => 'rent',
                'price'        => 95000,
                'address'      => 'Eulogio Rodriguez Jr. Ave',
                'city'         => 'Pasig',
                'state'        => 'Metro Manila',
                'country'      => 'Philippines',
                'zip_code'     => '1605',
                'latitude'     => 14.5762,
                'longitude'    => 121.0765,
                'bedrooms'     => 0,
                'bathrooms'    => 2,
                'area_sqft'    => 2000,
                'parking_spots'=> 4,
                'is_furnished' => true,
                'is_featured'  => false,
                'status'       => 'available',
                'cover_image'  => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
                'amenities'    => ['24/7 Access', 'PEZA Accredited', 'Fiber Internet', 'Generator', 'Elevator'],
            ],
        ];

        foreach ($properties2 as $data) {
            $user2->properties()->create($data);
        }
    }
}
